M48
; DRILL file KiCad 10.0.3 date 2026-07-13T09:48:06
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-13T09:48:06+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X192.0Y-113.0
T2
X132.5Y-89.0
X132.5Y-157.5
X195.0Y-89.0
X195.0Y-157.5
M30
